"use client";

import { useState } from "react";
import { DownloadSimpleIcon, CheckIcon } from "@phosphor-icons/react/dist/ssr";
import type { Confidence, Grounding, ToolStep } from "@/lib/chat-types";

/**
 * Exports an answer as a standalone brief.
 *
 * The assignment's optional requirement is to help prepare data for leadership
 * updates. The useful part of that is not formatting: it is that the figures
 * arrive with their provenance attached, so whoever presents them can defend
 * them. The file therefore carries the question, the answer, the queries that
 * produced it, the confidence rating and the grounding result.
 */
export function DownloadBrief({
  question,
  answer,
  steps,
  confidence,
  grounding,
}: {
  question: string;
  answer: string;
  steps: ToolStep[];
  confidence?: Confidence;
  grounding?: Grounding;
}) {
  const [done, setDone] = useState(false);

  const build = () => {
    const now = new Date();
    const stamp = now.toISOString().slice(0, 16).replace("T", " ");

    const lines = [
      `# ${question}`,
      "",
      `Prepared ${stamp} UTC from live monday.com boards.`,
      "",
      "---",
      "",
      answer.trim(),
      "",
      "---",
      "",
      "## How these figures were produced",
      "",
    ];

    if (steps.length) {
      for (const s of steps) {
        lines.push(`- \`${s.name}\` — ${s.summary ?? "no summary"}`);
      }
    } else {
      lines.push("- No queries were run for this answer.");
    }

    if (confidence) {
      lines.push("", "## Confidence", "");
      lines.push(`**${confidence.level}** (${confidence.score}/100)`, "");
      for (const b of confidence.basis) lines.push(`- ${b}`);
    }

    if (grounding) {
      lines.push("", "## Verification", "");
      lines.push(
        grounding.unverified.length
          ? `${grounding.grounded} of ${grounding.checked} figures traced back to a query. Not traced: ${grounding.unverified.join(", ")}. Check these before presenting them.`
          : `All ${grounding.checked} figures in this brief traced back to a monday.com query.`,
      );
    }

    lines.push(
      "",
      "---",
      "",
      "Generated by Skylark BI. Every figure is computed from a live read of the",
      "monday.com deals and work orders boards. No data is stored in the application.",
      "",
    );

    return lines.join("\n");
  };

  const download = () => {
    const blob = new Blob([build()], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `skylark-brief-${new Date().toISOString().slice(0, 10)}.md`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    // Revoked on the next tick so the navigation has started.
    setTimeout(() => URL.revokeObjectURL(url), 0);

    setDone(true);
    setTimeout(() => setDone(false), 1800);
  };

  return (
    <button
      onClick={download}
      className="inline-flex items-center gap-1.5 rounded-lg border border-[var(--line)] px-2.5 py-1.5 text-[11.5px] text-[var(--muted)] transition-all duration-200 hover:border-[var(--line-2)] hover:text-[var(--text)]"
      style={{ transitionTimingFunction: "var(--ease)" }}
    >
      {done ? (
        <CheckIcon size={13} weight="bold" style={{ color: "var(--success)" }} />
      ) : (
        <DownloadSimpleIcon size={13} weight="bold" />
      )}
      {done ? "Brief downloaded" : "Download brief"}
    </button>
  );
}
